'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'vi';

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.overview': 'Overview',
    'nav.ledger': 'Ledger',
    'nav.budget': 'Budget',
    'nav.subscriptions': 'Subscriptions',
    'nav.payroll': 'Payroll',
    'nav.invest': 'Invest',
    'nav.debts': 'Debts',
    'nav.config': 'Settings',
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.update': 'Update',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.total': 'Total',
    'common.noData': 'No data',
    'common.entries': 'entries',
    'common.active': 'active',
    'common.holdings': 'holdings',
    'common.budgets': 'budgets',
    'common.goals': 'goals',
    'common.overdue': 'overdue',
    'logout': 'Logout',
    'logout.confirm': 'Are you sure you want to logout?',
    'dashboard.payroll': 'Payroll',
    'dashboard.shifts': 'shifts',
    'dashboard.income': 'Income',
    'dashboard.expense': 'Expense',
    'dashboard.netFlow': 'Net Flow',
    'dashboard.savingsRate': 'Savings Rate',
    'dashboard.subscriptions': 'Subscriptions',
    'dashboard.due': 'DUE',
    'dashboard.vsLastMonth': 'vs Last Month',
    'dashboard.expenseBreakdown': 'Expense Breakdown',
    'dashboard.7DayActivity': 'Last 7 Days',
    'dashboard.activityLog': 'Activity Log',
    'dashboard.viewAll': 'VIEW ALL',
    'dashboard.noExpenseData': 'NO EXPENSE DATA',
    'dashboard.noActivity': 'NO ACTIVITY LOG',
    'ledger.masterLedger': 'MASTER LEDGER',
    'ledger.quickInput': 'Quick Input',
    'ledger.placeholder': 'Ex: "Ăn trưa 50k" or "+ Lương 15tr"',
    'ledger.commit': 'COMMIT',
    'ledger.executing': 'EXECUTING',
    'ledger.allFlows': 'ALL FLOWS',
    'ledger.inflow': '+ INFLOW',
    'ledger.outflow': '- OUTFLOW',
    'ledger.allCategories': 'ALL CATEGORIES',
    'ledger.search': 'SEARCH',
    'ledger.zeroRecords': 'ZERO MATCHING RECORDS',
    'ledger.awaitingInput': 'AWAITING INPUT',
    'budget.title': 'BUDGET & GOALS',
    'budget.addBudget': 'ADD BUDGET',
    'budget.addGoal': 'ADD GOAL',
    'budget.totalBudget': 'Total Budget',
    'budget.spent': 'Spent',
    'budget.goalsTarget': 'Goals Target',
    'budget.saved': 'Saved',
    'budget.budgets': 'BUDGETS',
    'budget.goals': 'GOALS',
    'budget.noBudgets': 'NO BUDGETS',
    'budget.noGoals': 'NO GOALS',
    'budget.limit': 'Limit',
    'budget.target': 'Target',
    'budget.contribute': 'Contribute',
    'budget.monthly': 'Monthly',
    'budget.weekly': 'Weekly',
    'budget.yearly': 'Yearly',
    'budget.remaining': 'remaining',
    'budget.completed': 'Completed!',
    'budget.daysLeft': 'days left',
    'budget.category': 'Category',
    'budget.deadline': 'Deadline',
    'budget.name': 'Name',
    'budget.amount': 'Amount',
    'budget.create': 'CREATE',
    'invest.title': 'INVESTMENTS',
    'invest.addInvestment': 'ADD INVESTMENT',
    'invest.totalValue': 'Total Value',
    'invest.cost': 'Cost',
    'invest.profitLoss': 'Profit/Loss',
    'invest.noInvestments': 'NO INVESTMENTS',
    'invest.stock': 'Stock',
    'invest.crypto': 'Crypto',
    'invest.bond': 'Bond',
    'invest.mutualFund': 'Mutual Fund',
    'invest.realEstate': 'Real Estate',
    'invest.quantity': 'Quantity',
    'invest.purchasePrice': 'Purchase Price',
    'invest.currentPrice': 'Current Price',
    'invest.symbol': 'Symbol',
    'invest.date': 'Date',
    'invest.type': 'Type',
    'debts.title': 'DEBTS',
    'debts.addDebt': 'ADD DEBT',
    'debts.totalDebt': 'Total Debt',
    'debts.paid': 'Paid',
    'debts.remaining': 'Remaining',
    'debts.overdue': 'Overdue',
    'debts.noDebts': 'NO DEBTS',
    'debts.lender': 'Lender',
    'debts.monthlyPayment': 'Monthly Payment',
    'debts.makePayment': 'MAKE PAYMENT',
    'debts.startDate': 'Start Date',
    'subs.title': 'SUBSCRIPTIONS',
    'subs.addSub': 'ADD SUBSCRIPTION',
    'subs.totalMonthly': 'Total Monthly',
    'subs.upcoming': 'UPCOMING',
    'subs.noSubs': 'NO SUBSCRIPTIONS',
    'payroll.title': 'PAYROLL',
    'payroll.totalSalary': 'Total Salary',
    'payroll.totalHours': 'Total Hours',
    'payroll.addShift': 'ADD SHIFT',
    'payroll.noShifts': 'NO SHIFTS',
    'settings.title': 'SYSTEM SETTINGS',
    'settings.changePin': 'Change PIN',
    'settings.currentPin': 'Current PIN',
    'settings.newPin': 'New PIN',
    'settings.confirmPin': 'Confirm PIN',
    'settings.updatePin': 'Update PIN',
    'settings.processing': 'Processing...',
    'settings.pinMismatch': 'PIN mismatch',
    'settings.pinLength': 'PIN must be 6 digits',
    'settings.exportData': 'Export Data',
    'settings.importData': 'Import Data',
    'settings.allData': 'All Data',
    'settings.transactionsOnly': 'Transactions Only',
    'settings.subscriptionsOnly': 'Subscriptions Only',
    'settings.systemInfo': 'System Information',
    'settings.version': 'Version',
    'settings.status': 'Status',
    'settings.database': 'Database',
    'settings.active': 'Active',
    'settings.chooseFile': 'Choose File',
    'settings.parametersLoaded': 'Parameters Loaded',
  },
  vi: {
    'nav.overview': 'Tổng quan',
    'nav.ledger': 'Sổ ghi',
    'nav.budget': 'Ngân sách',
    'nav.subscriptions': 'Đăng ký',
    'nav.payroll': 'Lương',
    'nav.invest': 'Đầu tư',
    'nav.debts': 'Nợ',
    'nav.config': 'Cài đặt',
    'common.loading': 'Đang tải...',
    'common.save': 'Lưu',
    'common.cancel': 'Hủy',
    'common.delete': 'Xóa',
    'common.edit': 'Sửa',
    'common.add': 'Thêm',
    'common.update': 'Cập nhật',
    'common.confirm': 'Xác nhận',
    'common.yes': 'Có',
    'common.no': 'Không',
    'common.total': 'Tổng',
    'common.noData': 'Không có dữ liệu',
    'common.entries': 'mục',
    'common.active': 'đang hoạt động',
    'common.holdings': 'danh mục',
    'common.budgets': 'ngân sách',
    'common.goals': 'mục tiêu',
    'common.overdue': 'quá hạn',
    'logout': 'Đăng xuất',
    'logout.confirm': 'Bạn chắc chắn muốn đăng xuất?',
    'dashboard.payroll': 'Lương',
    'dashboard.shifts': 'ca',
    'dashboard.income': 'Thu nhập',
    'dashboard.expense': 'Chi tiêu',
    'dashboard.netFlow': 'Dòng tiền',
    'dashboard.savingsRate': 'Tỷ lệ tiết kiệm',
    'dashboard.subscriptions': 'Đăng ký',
    'dashboard.due': 'SẮP ĐẾN',
    'dashboard.vsLastMonth': 'So với tháng trước',
    'dashboard.expenseBreakdown': 'Chi tiêu theo loại',
    'dashboard.7DayActivity': '7 ngày gần nhất',
    'dashboard.activityLog': 'Nhật ký hoạt động',
    'dashboard.viewAll': 'XEM TẤT CẢ',
    'dashboard.noExpenseData': 'KHÔNG CÓ DỮ LIỆU CHI',
    'dashboard.noActivity': 'KHÔNG CÓ HOẠT ĐỘNG',
    'ledger.masterLedger': 'SỔ GHI CHÍNH',
    'ledger.quickInput': 'Nhập nhanh',
    'ledger.placeholder': 'VD: "Ăn trưa 50k" hoặc "+ Lương 15tr"',
    'ledger.commit': 'GHI NHẬN',
    'ledger.executing': 'ĐANG XỬ LÝ',
    'ledger.allFlows': 'TẤT CẢ',
    'ledger.inflow': '+ THU',
    'ledger.outflow': '- CHI',
    'ledger.allCategories': 'TẤT CẢ LOẠI',
    'ledger.search': 'TÌM KIẾM',
    'ledger.zeroRecords': 'KHÔNG CÓ GIAO DỊCH',
    'ledger.awaitingInput': 'ĐANG CHỜ NHẬP',
    'budget.title': 'NGÂN SÁCH & MỤC TIÊU',
    'budget.addBudget': 'THÊM NGÂN SÁCH',
    'budget.addGoal': 'THÊM MỤC TIÊU',
    'budget.totalBudget': 'Tổng Ngân sách',
    'budget.spent': 'Đã chi',
    'budget.goalsTarget': 'Mục tiêu',
    'budget.saved': 'Đã tiết kiệm',
    'budget.budgets': 'NGÂN SÁCH',
    'budget.goals': 'MỤC TIÊU',
    'budget.noBudgets': 'CHƯA CÓ NGÂN SÁCH',
    'budget.noGoals': 'CHƯA CÓ MỤC TIÊU',
    'budget.limit': 'Giới hạn',
    'budget.target': 'Mục tiêu',
    'budget.contribute': 'Đóng góp',
    'budget.monthly': 'Hàng tháng',
    'budget.weekly': 'Hàng tuần',
    'budget.yearly': 'Hàng năm',
    'budget.remaining': 'còn lại',
    'budget.completed': 'Hoàn thành!',
    'budget.daysLeft': 'ngày',
    'budget.category': 'Loại',
    'budget.deadline': 'Hạn chót',
    'budget.name': 'Tên',
    'budget.amount': 'Số tiền',
    'budget.create': 'TẠO',
    'invest.title': 'ĐẦU TƯ',
    'invest.addInvestment': 'THÊM ĐẦU TƯ',
    'invest.totalValue': 'Tổng giá trị',
    'invest.cost': 'Giá vốn',
    'invest.profitLoss': 'Lãi/Lỗ',
    'invest.noInvestments': 'CHƯA CÓ ĐẦU TƯ',
    'invest.stock': 'Cổ phiếu',
    'invest.crypto': 'Crypto',
    'invest.bond': 'Trái phiếu',
    'invest.mutualFund': 'Quỹ',
    'invest.realEstate': 'Bất động sản',
    'invest.quantity': 'Số lượng',
    'invest.purchasePrice': 'Giá mua',
    'invest.currentPrice': 'Giá hiện tại',
    'invest.symbol': 'Mã',
    'invest.date': 'Ngày',
    'invest.type': 'Loại',
    'debts.title': 'NỢ',
    'debts.addDebt': 'THÊM NỢ',
    'debts.totalDebt': 'Tổng nợ',
    'debts.paid': 'Đã trả',
    'debts.remaining': 'Còn nợ',
    'debts.overdue': 'Quá hạn',
    'debts.noDebts': 'CHƯA CÓ NỢ',
    'debts.lender': 'Người cho vay',
    'debts.monthlyPayment': 'Trả hàng tháng',
    'debts.makePayment': 'THANH TOÁN',
    'debts.startDate': 'Ngày bắt đầu',
    'subs.title': 'ĐĂNG KÝ',
    'subs.addSub': 'THÊM ĐĂNG KÝ',
    'subs.totalMonthly': 'Tổng hàng tháng',
    'subs.upcoming': 'SẮP ĐẾN HẠN',
    'subs.noSubs': 'CHƯA CÓ ĐĂNG KÝ',
    'payroll.title': 'LƯƠNG',
    'payroll.totalSalary': 'Tổng lương',
    'payroll.totalHours': 'Tổng giờ',
    'payroll.addShift': 'THÊM CA',
    'payroll.noShifts': 'CHƯA CÓ CA LÀM',
    'settings.title': 'CẤU HÌNH HỆ THỐNG',
    'settings.changePin': 'Đổi mã PIN',
    'settings.currentPin': 'PIN hiện tại',
    'settings.newPin': 'PIN mới',
    'settings.confirmPin': 'Xác nhận PIN',
    'settings.updatePin': 'Cập nhật PIN',
    'settings.processing': 'Đang xử lý...',
    'settings.pinMismatch': 'PIN không khớp',
    'settings.pinLength': 'PIN phải 6 chữ số',
    'settings.exportData': 'Xuất dữ liệu',
    'settings.importData': 'Nhập dữ liệu',
    'settings.allData': 'Tất cả',
    'settings.transactionsOnly': 'Chỉ giao dịch',
    'settings.subscriptionsOnly': 'Chỉ đăng ký',
    'settings.systemInfo': 'Thông tin hệ thống',
    'settings.version': 'Phiên bản',
    'settings.status': 'Trạng thái',
    'settings.database': 'Cơ sở dữ liệu',
    'settings.active': 'Hoạt động',
    'settings.chooseFile': 'Chọn file',
    'settings.parametersLoaded': 'Đã tải tham số',
  }
};

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'vi',
  setLang: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>('vi');

  useEffect(() => {
    const saved = localStorage.getItem('flow9_lang') as Language;
    if (saved && (saved === 'en' || saved === 'vi')) {
      setLangState(saved);
    }
  }, []);

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('flow9_lang', newLang);
  };

  const t = (key: string): string => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
